name: thesis_project
description: A new Flutter project.

publish_to: "none"

version: 1.1.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  clay_containers: ^0.2.2
  cupertino_icons: ^1.0.0
  equatable: ^1.2.5
  google_fonts: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf

  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
